spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8
logging:
  level:
    root: INFO
    org.springframework.web: INFO
  config: classpath:logback-spring.xml
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    log-impl: com.dsy.sunshine.mybatis.log.SunshineMybatisLogger
log:
  level: INFO
  platform: sunshine
  env: dev
